# Generated by Django 4.2.13 on 2024-07-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_product_orgin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_catagory",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productcatagory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_orgin",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.ourworkingcompany",
            ),
        ),
    ]
