# Generated by Django 4.2.13 on 2024-07-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_cart_product_alter_cart_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productcatagory", old_name="catagory_img", new_name="img",
        ),
    ]
