# Generated by Django 4.0 on 2024-05-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('mrp', models.FloatField(blank=True, default=0.0, null=True)),
                ('our_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('Product_type', models.CharField(choices=[('pickl', 'pickl'), ('', ''), ('', '')], default=None, max_length=64)),
                ('product_orgin', models.CharField(choices=[('prime', 'prime'), ('applo', 'applo'), ('ITC', 'ITC'), ('Dona', 'Dona'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], default=None, max_length=64)),
                ('product_img', models.ImageField(default=None, upload_to='productImg')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('Product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='whosaleproduct.product')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
