# Generated by Django 4.2.13 on 2024-07-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coustomer",
            name="ph_no",
            field=models.IntegerField(default=None),
        ),
    ]
