# Generated by Django 4.2.13 on 2024-07-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_remove_coustomer_ph_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="coustomer", name="ph", field=models.IntegerField(default=True),
        ),
    ]
